pipelines:
  - name: local
    sources:
      - type: dev
        name: benchmark
        qps: 10000
        byteSize: 1024
        eventsTotal: -1
    sink:
      type: dev
      parallelism: 16
      host: "http://127.0.0.1:8080/loggie"
    concurrency:
      enable: true

