/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1beta1

import (
	"context"
	"time"

	v1beta1 "github.com/loggie-io/loggie/pkg/discovery/kubernetes/apis/loggie/v1beta1"
	scheme "github.com/loggie-io/loggie/pkg/discovery/kubernetes/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// LogConfigsGetter has a method to return a LogConfigInterface.
// A group's client should implement this interface.
type LogConfigsGetter interface {
	LogConfigs(namespace string) LogConfigInterface
}

// LogConfigInterface has methods to work with LogConfig resources.
type LogConfigInterface interface {
	Create(ctx context.Context, logConfig *v1beta1.LogConfig, opts v1.CreateOptions) (*v1beta1.LogConfig, error)
	Update(ctx context.Context, logConfig *v1beta1.LogConfig, opts v1.UpdateOptions) (*v1beta1.LogConfig, error)
	UpdateStatus(ctx context.Context, logConfig *v1beta1.LogConfig, opts v1.UpdateOptions) (*v1beta1.LogConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1beta1.LogConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1beta1.LogConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.LogConfig, err error)
	LogConfigExpansion
}

// logConfigs implements LogConfigInterface
type logConfigs struct {
	client rest.Interface
	ns     string
}

// newLogConfigs returns a LogConfigs
func newLogConfigs(c *LoggieV1beta1Client, namespace string) *logConfigs {
	return &logConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the logConfig, and returns the corresponding logConfig object, and an error if there is any.
func (c *logConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1beta1.LogConfig, err error) {
	result = &v1beta1.LogConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("logconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of LogConfigs that match those selectors.
func (c *logConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1beta1.LogConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1beta1.LogConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("logconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested logConfigs.
func (c *logConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("logconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a logConfig and creates it.  Returns the server's representation of the logConfig, and an error, if there is any.
func (c *logConfigs) Create(ctx context.Context, logConfig *v1beta1.LogConfig, opts v1.CreateOptions) (result *v1beta1.LogConfig, err error) {
	result = &v1beta1.LogConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("logconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(logConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a logConfig and updates it. Returns the server's representation of the logConfig, and an error, if there is any.
func (c *logConfigs) Update(ctx context.Context, logConfig *v1beta1.LogConfig, opts v1.UpdateOptions) (result *v1beta1.LogConfig, err error) {
	result = &v1beta1.LogConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("logconfigs").
		Name(logConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(logConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *logConfigs) UpdateStatus(ctx context.Context, logConfig *v1beta1.LogConfig, opts v1.UpdateOptions) (result *v1beta1.LogConfig, err error) {
	result = &v1beta1.LogConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("logconfigs").
		Name(logConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(logConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the logConfig and deletes it. Returns an error if one occurs.
func (c *logConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("logconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *logConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("logconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched logConfig.
func (c *logConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1beta1.LogConfig, err error) {
	result = &v1beta1.LogConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("logconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
