//
//Copyright 2021 Loggie Authors
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: pkg/sink/grpc/pb/loggie.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawLog []byte `protobuf:"bytes,1,opt,name=rawLog,proto3" json:"rawLog,omitempty"`
	// deprecated
	Header map[string][]byte `protobuf:"bytes,2,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// structured log data
	LogBody      map[string][]byte `protobuf:"bytes,3,rep,name=logBody,proto3" json:"logBody,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	IsSplit      bool              `protobuf:"varint,4,opt,name=isSplit,proto3" json:"isSplit,omitempty"`
	PackedHeader []byte            `protobuf:"bytes,5,opt,name=packedHeader,proto3" json:"packedHeader,omitempty"`
}

func (x *LogMsg) Reset() {
	*x = LogMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_sink_grpc_pb_loggie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogMsg) ProtoMessage() {}

func (x *LogMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sink_grpc_pb_loggie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogMsg.ProtoReflect.Descriptor instead.
func (*LogMsg) Descriptor() ([]byte, []int) {
	return file_pkg_sink_grpc_pb_loggie_proto_rawDescGZIP(), []int{0}
}

func (x *LogMsg) GetRawLog() []byte {
	if x != nil {
		return x.RawLog
	}
	return nil
}

func (x *LogMsg) GetHeader() map[string][]byte {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *LogMsg) GetLogBody() map[string][]byte {
	if x != nil {
		return x.LogBody
	}
	return nil
}

func (x *LogMsg) GetIsSplit() bool {
	if x != nil {
		return x.IsSplit
	}
	return false
}

func (x *LogMsg) GetPackedHeader() []byte {
	if x != nil {
		return x.PackedHeader
	}
	return nil
}

type LogResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success  bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Count    int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	ErrorMsg string `protobuf:"bytes,3,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
}

func (x *LogResp) Reset() {
	*x = LogResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_sink_grpc_pb_loggie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResp) ProtoMessage() {}

func (x *LogResp) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_sink_grpc_pb_loggie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResp.ProtoReflect.Descriptor instead.
func (*LogResp) Descriptor() ([]byte, []int) {
	return file_pkg_sink_grpc_pb_loggie_proto_rawDescGZIP(), []int{1}
}

func (x *LogResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LogResp) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *LogResp) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

var File_pkg_sink_grpc_pb_loggie_proto protoreflect.FileDescriptor

var file_pkg_sink_grpc_pb_loggie_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x69, 0x6e, 0x6b, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f,
	0x70, 0x62, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0xbc, 0x02, 0x0a, 0x06, 0x4c, 0x6f, 0x67, 0x4d, 0x73, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x77, 0x4c, 0x6f, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x72, 0x61, 0x77, 0x4c, 0x6f, 0x67, 0x12, 0x30, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x4c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x33, 0x0a, 0x07, 0x6c, 0x6f,
	0x67, 0x42, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x72,
	0x70, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x4d, 0x73, 0x67, 0x2e, 0x4c, 0x6f, 0x67, 0x42, 0x6f, 0x64,
	0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x6c, 0x6f, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x69, 0x73, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x69, 0x73, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x70, 0x61, 0x63,
	0x6b, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x1a, 0x39, 0x0a,
	0x0b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3a, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x42,
	0x6f, 0x64, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x55, 0x0a, 0x07, 0x4c, 0x6f, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x73, 0x67, 0x32, 0x3a, 0x0a, 0x0a, 0x4c,
	0x6f, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2c, 0x0a, 0x09, 0x6c, 0x6f, 0x67,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x6f,
	0x67, 0x4d, 0x73, 0x67, 0x1a, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x6f, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x00, 0x28, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_sink_grpc_pb_loggie_proto_rawDescOnce sync.Once
	file_pkg_sink_grpc_pb_loggie_proto_rawDescData = file_pkg_sink_grpc_pb_loggie_proto_rawDesc
)

func file_pkg_sink_grpc_pb_loggie_proto_rawDescGZIP() []byte {
	file_pkg_sink_grpc_pb_loggie_proto_rawDescOnce.Do(func() {
		file_pkg_sink_grpc_pb_loggie_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_sink_grpc_pb_loggie_proto_rawDescData)
	})
	return file_pkg_sink_grpc_pb_loggie_proto_rawDescData
}

var file_pkg_sink_grpc_pb_loggie_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_sink_grpc_pb_loggie_proto_goTypes = []interface{}{
	(*LogMsg)(nil),  // 0: grpc.LogMsg
	(*LogResp)(nil), // 1: grpc.LogResp
	nil,             // 2: grpc.LogMsg.HeaderEntry
	nil,             // 3: grpc.LogMsg.LogBodyEntry
}
var file_pkg_sink_grpc_pb_loggie_proto_depIdxs = []int32{
	2, // 0: grpc.LogMsg.header:type_name -> grpc.LogMsg.HeaderEntry
	3, // 1: grpc.LogMsg.logBody:type_name -> grpc.LogMsg.LogBodyEntry
	0, // 2: grpc.LogService.logStream:input_type -> grpc.LogMsg
	1, // 3: grpc.LogService.logStream:output_type -> grpc.LogResp
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_sink_grpc_pb_loggie_proto_init() }
func file_pkg_sink_grpc_pb_loggie_proto_init() {
	if File_pkg_sink_grpc_pb_loggie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_sink_grpc_pb_loggie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_sink_grpc_pb_loggie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_sink_grpc_pb_loggie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_sink_grpc_pb_loggie_proto_goTypes,
		DependencyIndexes: file_pkg_sink_grpc_pb_loggie_proto_depIdxs,
		MessageInfos:      file_pkg_sink_grpc_pb_loggie_proto_msgTypes,
	}.Build()
	File_pkg_sink_grpc_pb_loggie_proto = out.File
	file_pkg_sink_grpc_pb_loggie_proto_rawDesc = nil
	file_pkg_sink_grpc_pb_loggie_proto_goTypes = nil
	file_pkg_sink_grpc_pb_loggie_proto_depIdxs = nil
}
