// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0-devel
// 	protoc        v3.6.1
// source: stream_storage_iter.proto

package storage

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamIter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash           uint64               `protobuf:"varint,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Offset         int64                `protobuf:"varint,2,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Done           bool                 `protobuf:"varint,4,opt,name=Done,proto3" json:"Done,omitempty"`
	Seq            uint64               `protobuf:"varint,5,opt,name=Seq,proto3" json:"Seq,omitempty"`
	Line           uint64               `protobuf:"varint,6,opt,name=Line,proto3" json:"Line,omitempty"`
	Mtime          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=Mtime,proto3" json:"Mtime,omitempty"`
	DataListUptime *timestamp.Timestamp `protobuf:"bytes,8,opt,name=DataListUptime,proto3" json:"DataListUptime,omitempty"`
}

func (x *StreamIter) Reset() {
	*x = StreamIter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_stream_storage_iter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamIter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamIter) ProtoMessage() {}

func (x *StreamIter) ProtoReflect() protoreflect.Message {
	mi := &file_stream_storage_iter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamIter.ProtoReflect.Descriptor instead.
func (*StreamIter) Descriptor() ([]byte, []int) {
	return file_stream_storage_iter_proto_rawDescGZIP(), []int{0}
}

func (x *StreamIter) GetHash() uint64 {
	if x != nil {
		return x.Hash
	}
	return 0
}

func (x *StreamIter) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *StreamIter) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *StreamIter) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StreamIter) GetLine() uint64 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *StreamIter) GetMtime() *timestamp.Timestamp {
	if x != nil {
		return x.Mtime
	}
	return nil
}

func (x *StreamIter) GetDataListUptime() *timestamp.Timestamp {
	if x != nil {
		return x.DataListUptime
	}
	return nil
}

var File_stream_storage_iter_proto protoreflect.FileDescriptor

var file_stream_storage_iter_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x5f, 0x69, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d,
	0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe8, 0x01, 0x0a,
	0x0a, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x49, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x48, 0x61, 0x73, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x4f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x44, 0x6f, 0x6e, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x53,
	0x65, 0x71, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x53, 0x65, 0x71, 0x12, 0x12, 0x0a,
	0x04, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x4c, 0x69, 0x6e,
	0x65, 0x12, 0x30, 0x0a, 0x05, 0x4d, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x05, 0x4d, 0x74,
	0x69, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x55,
	0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x4c, 0x69, 0x73,
	0x74, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x6f, 0x67, 0x67, 0x69, 0x65, 0x2d, 0x69, 0x6f, 0x2f,
	0x6c, 0x6f, 0x67, 0x67, 0x69, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x2f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2f, 0x75, 0x74, 0x69,
	0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_stream_storage_iter_proto_rawDescOnce sync.Once
	file_stream_storage_iter_proto_rawDescData = file_stream_storage_iter_proto_rawDesc
)

func file_stream_storage_iter_proto_rawDescGZIP() []byte {
	file_stream_storage_iter_proto_rawDescOnce.Do(func() {
		file_stream_storage_iter_proto_rawDescData = protoimpl.X.CompressGZIP(file_stream_storage_iter_proto_rawDescData)
	})
	return file_stream_storage_iter_proto_rawDescData
}

var file_stream_storage_iter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stream_storage_iter_proto_goTypes = []interface{}{
	(*StreamIter)(nil),          // 0: StreamIter
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_stream_storage_iter_proto_depIdxs = []int32{
	1, // 0: StreamIter.Mtime:type_name -> google.protobuf.Timestamp
	1, // 1: StreamIter.DataListUptime:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stream_storage_iter_proto_init() }
func file_stream_storage_iter_proto_init() {
	if File_stream_storage_iter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_stream_storage_iter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamIter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_stream_storage_iter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stream_storage_iter_proto_goTypes,
		DependencyIndexes: file_stream_storage_iter_proto_depIdxs,
		MessageInfos:      file_stream_storage_iter_proto_msgTypes,
	}.Build()
	File_stream_storage_iter_proto = out.File
	file_stream_storage_iter_proto_rawDesc = nil
	file_stream_storage_iter_proto_goTypes = nil
	file_stream_storage_iter_proto_depIdxs = nil
}
