# 动态 sink 并发配置使用示例
# example config for sink adaptive concurrency
pipelines:
  - name: local
    sources:
      - type: dev
        name: benchmark
        qps: 10000
        byteSize: 1024
        eventsTotal: -1
    sink:
      type: dev
      parallelism: 16
      printEvents: true
      concurrency:
        enable: true
        rtt:
          blockJudgeThreshold: 120%
          newRttWeigh: 0.4
        goroutine:
          initThreshold: 8
          maxGoroutine: 20
          unstableTolerate: 3
          channelLenOfCap: 0.4


